---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stunner.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations: {{ include "stunner.metadata.annotations" . | nindent 4 }}  
spec:
  selector:
    matchLabels:
      {{- include "stunner.labels" . | nindent 6 }}
  replicas: {{ .Values.stunner.deployment.replica }}
  template:
    metadata:
      labels:
        {{- include "stunner.labels" . | nindent 8 }}
    spec:
      {{- include "stunner.stunnerGatewayOperator.volume" . | indent 6 }}
      terminationGracePeriodSeconds: {{ .Values.stunner.deployment.container.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Values.stunner.deployment.container.name }}
        image: "{{ .Values.stunner.deployment.container.image.repository }}{{ .Values.stunner.deployment.container.image.name }}:{{ .Values.stunner.deployment.container.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.stunner.deployment.container.image.pullPolicy }}
        {{- include "stunner.stunnerGatewayOperator.args" . | indent 8 }}
        resources: {{- toYaml .Values.stunner.deployment.container.resources | nindent 10 }}
        livenessProbe: {{- toYaml .Values.stunner.deployment.container.livenessProbe | nindent 10 }}
        readinessProbe: {{- toYaml .Values.stunner.deployment.container.readinessProbe | nindent 10 }}
{{- if eq .Values.stunner.deployment.monitoring.enabled true}}
        ports:
          - name: {{ .Values.stunner.deployment.monitoring.portName }}
            containerPort: {{ .Values.stunner.deployment.monitoring.containerPort }}
{{- end}}
{{- if eq .Values.stunner.deployment.container.netdebug.enabled true}}
      - name: net-debug
        image: l7mp/net-debug:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
{{- end}}
      {{- with .Values.stunner.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stunner.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
---
