---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prometheus-operator
  labels:
    metrics: stunner
  namespace: {{ .Values.namespace }}
spec:
  podMetricsEndpoints:
  - honorLabels: True
    interval: 5s
    port: "metrics-port"
    path: "/metrics"
  selector:
    matchLabels:
      app: stunner
  namespaceSelector:
    #any: true
    matchNames:
      - stunner
      - stunner-system
      - default
      - {{ .Values.namespace }}
