---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: {{ .Values.selectorLabels.component }}
    app.kubernetes.io/name: {{ .Values.selectorLabels.name }}
    app.kubernetes.io/version: {{ .Values.selectorLabels.version }}
  name: prometheus-operator
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - name: "metrics-port"
    port:  8080
  selector:
    app.kubernetes.io/component: {{ .Values.selectorLabels.component }}
    app.kubernetes.io/name: {{ .Values.selectorLabels.name }}
