stunnerGatewayOperator:
  enabled: true
  namespace: stunner-gateway-operator-system
  deployment:
    name: stunner-gateway-operator
    container:
      image:
        repository: ""
        name: l7mp/stunner-gateway-operator
        pullPolicy: Always
        tag: latest
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 128Mi

stunner:
  namespace: default