# Default values for stunner-gateway-operator.

#To set the namespace for the deployment use the --namespace=<your-namespace> --create-namespace
#additional commands when installing your release
#It will create the desired namespace if not present

stunnerGatewayOperator:
  enabled: true
  deployment:
    name: stunner-gateway-operator
    container:
      manager:
        image:
          repository: ""
          name: l7mp/stunner-gateway-operator
          pullPolicy: Always
          tag: 0.12.0
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 128Mi
      kubeRbacProxy: 
        image:
          name: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0