{{- if eq .Values.stunnerAuthService.enabled true}}
{{- with .Values.stunnerAuthService }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stunner-auth-service-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stunner-auth
  namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stunner-auth-service-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stunner-auth-service-role
subjects:
  - kind: ServiceAccount
    name: stunner-auth
    namespace: {{ $.Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stunner-auth
  namespace: {{ $.Release.Namespace }}
  labels:
    app: stunner-auth
spec:
  selector:
    matchLabels:
      app: stunner-auth
  replicas: 1
  template:
    metadata:
      labels:
        app: stunner-auth
    spec:
      serviceAccountName: stunner-auth
      terminationGracePeriodSeconds: 10
      containers:
        - name: stunner-auth-server
          image: "{{ .deployment.container.authService.image.repository }}{{ .deployment.container.authService.image.name }}:{{ .deployment.container.authService.image.tag }}"
          imagePullPolicy: Always
          command: [ "./manager" ]
          args:
          {{- range $.Values.stunnerAuthService.deployment.container.authService.args }}
          -  {{ . }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
      nodeSelector: {{- toYaml .deployment.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .deployment.tolerations | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: stunner-auth
  namespace: {{ $.Release.Namespace }}
  labels:
    app: stunner-auth
spec:
  selector:
    app: stunner-auth
  ports:
    - name: stunner-auth-server
      port: 8088
  type: ClusterIP
{{- end }}
{{- end -}}